# Use the latest Node.js version (e.g., 18-alpine or 20-alpine)
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# # Install NestJS CLI globally using npm (optional, if you need it for your project)
# RUN npm install -g @nestjs/cli

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./
COPY printzy-bcf06-firebase-adminsdk-r8sbf-600876281b.json ./

# Install dependencies using npm
RUN npm ci


# Copy the remaining application files
COPY . .


USER node
# Expose port 3020
EXPOSE 3020

# Start the application in development mode using npm
CMD ["npm", "run", "start:dev"]
