# Use the latest Node.js version (e.g., 18-alpine or 20-alpine)
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies using npm
RUN npm ci

# Install NestJS CLI globally using npm (optional, if you need it for your project)
RUN npm install -g @nestjs/cli

# Copy the remaining application files
COPY . .

# Expose port 3020
EXPOSE 3020

# Start the application in development mode using npm
CMD ["npm", "run", "start:dev"]
