# Use the latest Node.js version (e.g., 18-alpine or 20-alpine)
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# # Install NestJS CLI globally using npm (optional, if you need it for your project)
# RUN npm install -g @nestjs/cli

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json yarn.lock ./
COPY  poised-shift-422808-d9-firebase-adminsdk-7mpf9-965a8b765c.json ./

# Install dependencies using npm
RUN yarn


# Copy the remaining application files
COPY . .


USER node
# Expose port 3020
EXPOSE 3020

# Start the application in development mode using npm
CMD ["npm", "run", "start:dev"]
